Repository FRONTENDBOOTCAMP-13th/Final-06-6PM, pull requests merged in 2025-07, with the labels that each got.

#12 💄 style: 게시판/댓글 아이템 컴포넌트 제작
  src/components/comment-item-component.tsx
  src/components/free-item-component.tsx
Labels: 🎨 style

#31 💄 style: random-item 컴포넌트 구현 이미지 추가
  public/sea.img
  src/components/ui/random-item.tsx
Labels: 🎨 style

#39 ♻️ refactor: 컴포넌트 확인용 파일 재설정
  src/app/components/chj/page.tsx
  src/app/components/msi/page.tsx
  src/app/components/njs/page.tsx
  src/app/components/psy/page.tsx
  src/app/components/sah/page.tsx
  src/components/ui/BtnIcon.tsx
  src/components/ui/drawerItem.tsx
  src/components/ui/random-item.tsx
  src/components/ui/selectMenu2.tsx
  src/components/ui/selectMenu3.tsx
Labels: 🛠️ refactor

#35 💄 style: view-item 컴포넌트 구현
  src/components/ui/view-item.tsx
Labels: 🎨 style

#61 🐳 chore: 페이지 폴더구조 재세팅
  src/app/admin/posts/page.tsx
  src/app/auth/login/page.tsx
  src/app/auth/page.tsx
  src/app/auth/signup/page.tsx
  src/app/favicon.ico
  src/app/feed/[id]/edit/page.tsx
  src/app/feed/[id]/page.tsx
  src/app/feed/new/page.tsx
  src/app/feed/page.tsx
  src/app/mypage/bookmark/page.tsx
  src/app/mypage/page.tsx
  src/app/mypage/review/page.tsx
  src/app/page.tsx
  src/app/photomap/page.tsx
  src/app/plan/[id]/edit/page.tsx
  src/app/plan/[id]/page.tsx
  src/app/plan/new/page.tsx
  src/app/plan/page.tsx
  src/app/post/page.tsx
  src/app/review/[id]/edit/page.tsx
  src/app/review/[id]/page.tsx
  src/app/review/new/page.tsx
  src/app/review/page.tsx
  src/app/signup/page.tsx
Labels: ⚙️ setting

#60 💄 style : 인풋 컴포넌트 제작
  src/app/components/sah/page.tsx
  src/components/ui/input.tsx
  src/components/ui/search-input.tsx
  src/components/ui/textarea.tsx
Labels: 🎨 style

#67 💄 style: 나의 북마크 페이지 레이아웃 수정용 커밋
  src/app/mypage/bookmark/page.tsx
Labels: 🎨 style

#65 💄 style: 여행일정 지역 선택 페이지 제작
  src/app/plan/dates/page.tsx
  src/app/plan/page.tsx
Labels: 🎨 style

#68 💄 style: 마이페이지 레이아웃 구성
  src/app/mypage/page.tsx
Labels: 🎨 style

#79 💄 style: 홈 페이지 레이아웃 구성
  src/app/home/page.tsx
  src/components/ui/drawerItem.tsx
Labels: 🎨 style

#81 💄 style: 로그인 페이지 레이아웃 구성
  public/images/log.png
  src/app/auth/login/page.tsx
Labels: 🎨 style

#78 💄 style: 마이페이지 북마크와 리뷰 초안
  src/app/mypage/bookmark/[id]/page.tsx
  src/app/mypage/bookmark/page.tsx
  src/app/mypage/review/depth1/page.tsx
  src/app/mypage/review/depth2/page.tsx
  src/app/mypage/review/page.tsx
  src/components/ui/reviewItem.tsx
Labels: 🎨 style

#91 ♻️ refactor: feedpages 스타일 전체적 조정
  public/images/user4.png
  src/app/feed/[id]/layout.tsx
  src/app/feed/[id]/page.tsx
  src/app/feed/page.tsx
  src/app/review/detail/page.tsx
  src/app/review/new/layout.tsx
  src/app/review/new/page.tsx
  src/app/review/success/page.tsx
  src/components/ui/Btn.tsx
  src/components/ui/dropdownItem.tsx
Labels: 🎨 style, 🛠️ refactor, ✨feat

#93 ♻️ refactor: 로그인 페이지 리팩토링
  src/app/auth/layout.tsx
  src/app/auth/login/page.tsx
  src/components/Footer.tsx
Labels: 🎨 style, 🛠️ refactor

#96 ♻️ refactor: 마이페이지 리팩토링
  src/app/mypage/edit/page.tsx
  src/components/ui/profileItem.tsx
  src/components/ui/profileItemedit.tsx
Labels: 🎨 style, 🛠️ refactor

#99 🐳 chore: 데이터구조 설정
  api/bruno/PROJECT-6pm/bruno.json
  api/bruno/PROJECT-6pm/collection.bru
  api/bruno/PROJECT-6pm/environments/6pm.bru
  api/bruno/PROJECT-6pm/여행계획 목록상세조회.bru
  api/bruno/PROJECT-6pm/여행계획 목록전체조회.bru
  api/bruno/PROJECT-6pm/여행후기 목록상세조회-일자별.bru
  api/bruno/PROJECT-6pm/여행후기 목록상세조회-장소별.bru
  api/bruno/PROJECT-6pm/여행후기 목록상세조회-전체.bru
  api/bruno/PROJECT-6pm/여행후기 목록조회-일자별.bru
  api/bruno/PROJECT-6pm/여행후기 목록조회-장소별.bru
  api/bruno/PROJECT-6pm/여행후기 목록조회-전체.bru
  api/bruno/PROJECT-6pm/회원정보조회.bru
  api/dbinit/team/data.js
  eslint.config.mjs
Labels: ⚙️ setting

#104 ♻️ refactor: 컴포넌트 리팩토링 진행
  package-lock.json
  package.json
  public/images/sea.png
  public/images/user5.png
  src/app/components/chj/page.tsx
  src/app/components/msi/page.tsx
  src/app/components/njs/page.tsx
  src/app/components/psy/page.tsx
  src/app/components/sah/page.tsx
  src/app/feed/[id]/page.tsx
  src/app/feed/page.tsx
  src/app/home/layout.tsx
  src/app/home/page.tsx
  src/app/layout.tsx
  src/app/mypage/bookmark/[id]/page.tsx
  src/app/mypage/bookmark/page.tsx
  src/app/mypage/edit/page.tsx
  src/app/mypage/layout.tsx
  src/app/mypage/page.tsx
  src/app/mypage/review/depth1/page.tsx
  src/app/mypage/review/depth2/page.tsx
  src/app/mypage/review/page.tsx
  src/app/page.tsx
  src/app/plan/page.tsx
  src/app/plan/search/page.tsx
  src/app/review/detail/page.tsx
  src/components/Modal.tsx
  src/components/feature/drawerBtn.tsx
  src/components/feature/drawerItem.tsx
  src/components/feature/drawerSelectImg.tsx
  src/components/feature/locationModal.tsx
  src/components/feature/placePlusItem.tsx
  src/components/feature/planList.tsx
  src/components/feature/scheduleRegister.tsx
  src/components/feature/selectMenu2.tsx
  src/components/feature/selectMenu3.tsx
  src/components/feature/toggleComponents.tsx
  src/components/feature/viewItem.tsx
  src/components/form/profileItemEdit.tsx
  src/components/form/searchInput.tsx
  src/components/ui/bookmarkItem.tsx
  src/components/ui/commentItem.tsx
  src/components/ui/dayItem.tsx
  src/components/ui/drawerBtn.tsx
  src/components/ui/drawerItem.tsx
  src/components/ui/drawerSelectImg.tsx
  src/components/ui/input.tsx
  src/components/ui/placePlus.tsx
  src/components/ui/planList.tsx
  src/components/ui/planListItem.tsx
  src/components/ui/profileItem.tsx
  src/components/ui/profileItemEdit.tsx
  src/components/ui/randomItem.tsx
  src/components/ui/reviewItem.tsx
  src/components/ui/scheduleRegister.tsx
  src/components/ui/searchInput.tsx
  src/components/ui/textarea.tsx
  src/components/ui/toggleComponents.tsx
  src/styles/globals.css
Labels: 🎨 style, 🛠️ refactor, ✨feat

#110 💄 style: view-item 컴포넌트 스타일 변경 및 셀렉트 컴포넌트 추가
  src/app/feed/[id]/page.tsx
  src/app/feed/page.tsx
  src/app/mypage/bookmark/[id]/page.tsx
  src/app/mypage/bookmark/page.tsx
  src/app/mypage/page.tsx
  src/app/mypage/review/depth1/page.tsx
  src/app/mypage/review/depth2/page.tsx
  src/app/mypage/review/page.tsx
  src/components/feature/drawerBtn.tsx
  src/components/feature/placePlusItem.tsx
  src/components/feature/selectBookmark.tsx
  src/components/feature/selectMypage.tsx
  src/components/feature/selectReview.tsx
  src/components/feature/viewItem.tsx
  src/components/ui/dayItem.tsx
Labels: 🎨 style, 🛠️ refactor

#113 💄 style: 3뎁스에 따른 페이지 데이터 구현
  src/app/auth/login/page.tsx
  src/app/home/page.tsx
  src/app/mypage/bookmark/[id]/page.tsx
  src/app/mypage/edit/page.tsx
  src/app/mypage/page.tsx
  src/app/photomap/page.tsx
  src/app/plan/TravelPage.tsx
  src/app/plan/page.tsx
  src/app/plan/success/page.tsx
  src/app/review/detail/layout.tsx
  src/app/review/detail/page.tsx
  src/app/review/new/ReviewPage.tsx
  src/components/feature/destinationCard.tsx
  src/components/feature/selectWriteReview.tsx
  src/components/feature/viewItem.tsx
  src/components/form/loginForm.tsx
  src/components/form/profileItemEdit.tsx
  src/components/form/reviewContent.tsx
  src/components/form/reviewDetailForm.tsx
  src/components/form/reviewFormAll.tsx
  src/components/form/reviewImg.tsx
  src/components/form/reviewSelect.tsx
  src/components/form/reviewStar.tsx
  src/components/form/reviewTag.tsx
  src/components/form/reviewTitle.tsx
Labels: 🎨 style, 🛠️ refactor, ✨feat

#114 🐳 chore: data.js 업데이트
  api/dbinit/team/data.js
Labels: ⚙️ setting

#115 🐳 chore: 브루노 연동 테스트
  src/app/components/chj/getpost/page.tsx
Labels: ✅ test

#116 ✨ feat: 날씨 api 연동
  src/app/home/page.tsx
  src/hook/useWeather.tsx
  src/lib/api/weather.ts
Labels: ✨feat

#118 ♻️ refactor: 컴포넌트 및 페이지 경로 변경
  src/app/components/msi/page.tsx
  src/app/feed/page.tsx
  src/app/home/page.tsx
  src/app/mypage/bookmark/page.tsx
  src/app/plan/search/page.tsx
  src/app/review/new/ReviewPage.tsx
  src/app/review/new/page.tsx
  src/components/feature/dropdownItem.tsx
  src/components/feature/placePlusItem.tsx
  src/components/feature/tagItem.tsx
  src/components/feature/weatherApi.tsx
  src/components/form/reviewTag.tsx
  src/components/ui/planListItem.tsx
  src/components/ui/removeTag.tsx
Labels: 🛠️ refactor

#126 ✨ feat: 위치·날짜 표시, 날씨 API 연동
  src/app/home/page.tsx
  src/components/feature/serverLocation.tsx
  src/lib/api/utils/getTodayString.ts
  src/lib/api/utils/getTodayYYYYMMDD.ts
  src/lib/api/weather.ts
Labels: ✨feat

#128 🐳 chore: travelAPI fetch방식 수정
  src/app/components/chj/getpost/page.tsx
  src/app/components/psy/travel/page.tsx
  src/data/actions/post.ts
  src/data/actions/travel.ts
  src/data/functions/fetchTravel.ts
  src/data/functions/posts.ts
  src/hook/useAxiosInstance.tsx
  src/hook/useTravelInstance.tsx
  src/types/api.ts
  src/types/index.ts
  src/types/plan.ts
  src/types/travel.ts
  src/types/travelApi.ts
  src/types/user.ts
Labels: ⚙️ setting

#133 💄 style: swiper pagination 스타일 변경
  src/components/feature/viewItem.tsx
Labels: 🎨 style

#136 ✨ feat: 캘린더 추가, 세션 스토리지 연동
  src/app/plan/TravelPage.tsx
  src/app/plan/dates/layout.tsx
  src/app/plan/dates/page.tsx
  src/app/plan/edit/layout.tsx
  src/app/plan/search/layout.tsx
  src/app/plan/view/layout.tsx
  src/components/feature/backButton.tsx
  src/components/feature/planCalendar.tsx
Labels: ✨feat

#135 🐳 chore: 날씨 API 데이터패칭 방식 수정
  src/app/home/page.tsx
  src/components/feature/locationWeatherBox.tsx
  src/components/feature/serverLocation.tsx
  src/components/feature/weatherApi.tsx
  src/data/actions/weather.ts
  src/data/functions/fetchWeather.ts
  src/hook/useWeather.tsx
  src/lib/api/baseTime.ts
  src/lib/api/todayDate.ts
  src/lib/api/todayString.ts
  src/lib/api/togrid.ts
  src/lib/api/weather.ts
  src/types/weather.ts
Labels: ⚙️ setting, ✅ test, 🛠️ refactor

#151 🐳 chore : Bruno 세팅관련 재조정
  api/bruno/PROJECT-6pm/01_회원/로그인.bru
  api/bruno/PROJECT-6pm/02_여행일정/나의 여행계획 목록전체조회.bru
  api/bruno/PROJECT-6pm/02_여행일정/여행일정 등록.bru
  api/bruno/PROJECT-6pm/collection.bru
  api/bruno/PROJECT-6pm/environments/6pm.bru
Labels: ⚙️ setting

#154 🧪 test : 지도 기능 추가
  .vscode/settings.json
  src/app/photomap/view/mapcom/depth/koreaMap2.tsx
  src/app/photomap/view/mapcom/depth/koreaMapImg.tsx
  src/app/photomap/view/mapcom/depth/paths.tsx
  src/app/photomap/view/mapcom/depth/sigrealfinal.svg
  src/app/photomap/view/page.tsx
Labels: ✅ test

#160 ✨ feat: 마이페이지 사용자 여행 계획 조회 구현
  public/images/place-default.webp
  public/images/user-default.webp
  src/app/review/new/ReviewPage.tsx
  src/components/feature/destinationCard.tsx
  src/components/feature/selectMypage.tsx
  src/components/form/plan/planRegion.tsx
  src/components/ui/dayItem.tsx
  src/components/ui/profileItem.tsx
  src/lib/data/destinationList.ts
Labels: 🎨 style, 🛠️ refactor, ✨feat

#164 🐛 bug: 배포 관련 오류 처리
  src/app/components/njs/page.tsx
  src/components/feature/locationWeatherBox.tsx
  src/components/feature/searchRegion.tsx
  src/components/feature/serverLocation.tsx
  src/components/form/loginForm.tsx
  src/data/functions/weather.ts
Labels: 🐞 bug

#168 ✨ feat: 피드페이지 후기 조회
  src/app/feed/page.tsx
  src/components/feature/viewItem.tsx
  src/data/functions/plan.ts
Labels: ✨feat

#165 🐳 chore: 여행후기 관련 데이터set 조정
  api/bruno/PROJECT-6pm/03_여행후기/01_등록/여행후기 등록-일자별.bru
  api/bruno/PROJECT-6pm/03_여행후기/01_등록/여행후기 등록-장소별.bru
  api/bruno/PROJECT-6pm/03_여행후기/01_등록/여행후기 등록-전체.bru
  api/bruno/PROJECT-6pm/environments/6pm.bru
  api/dbinit/team/data.js
Labels: ⚙️ setting

#173 🐛 bug: 날씨API - Client 로 재조정
  next.config.ts
  src/components/feature/locationWeatherBox.tsx
  src/components/feature/serverLocation.tsx
  src/data/functions/weather.ts
  src/lib/api/weather.ts
Labels: 🐞 bug

#180 ✨ feat: 미리보기 페이지에서 일정 추가 버튼 숨김기능 구현
  next.config.ts
  src/app/plan/edit/preview/page.tsx
  src/components/feature/fillScheduleCard.tsx
  src/components/form/plan/planDetailForm.tsx
  src/components/form/plan/planRegion.tsx
  src/components/plan/scheduleContent.tsx
  src/components/plan/searchAll.tsx
  src/components/ui/dayScheduleCard.tsx
  src/components/ui/planListItem.tsx
  src/data/functions/travel.ts
  src/hook/usePlanSchedule.ts
  src/types/plan.ts
Labels: 🛠️ refactor, ✨feat

#186 ✨ feat: 폼 등록 관련 일자별, 장소별 등록 기능 추가
  src/app/components/chj/getpost/devide/fetchPlanDetail.ts
  src/app/components/chj/getpost/page.tsx
  src/app/components/chj/getpost/types/plan.ts
  src/app/components/chj/page.tsx
  src/app/components/msi/page.tsx
  src/app/components/njs/page.tsx
  src/app/components/page.tsx
  src/app/components/psy/page.tsx
  src/app/components/psy/travel/page.tsx
  src/app/components/sah/page.tsx
  src/app/review/success/page.tsx
  src/components/feature/selectWriteReview.tsx
  src/components/form/reviewDetailForm.tsx
  src/data/actions/review.ts
Labels: ✨feat

#189 ✨ feat: 마이페이지 일정별 리뷰 필터링 추가
  api/bruno/PROJECT-6pm/03_여행후기/02_조회/여행후기 상세조회-일자별.bru
  api/bruno/PROJECT-6pm/03_여행후기/02_조회/여행후기 상세조회-장소별.bru
  api/bruno/PROJECT-6pm/03_여행후기/02_조회/여행후기 상세조회-전체.bru
  src/app/mypage/review/page.tsx
  src/components/feature/selectReview.tsx
  src/components/feature/selectReviewTab.tsx
Labels: 🛠️ refactor, ✨feat

#188 ✨ feat: 일차별 계획(댓글) 등록 제작
  src/app/plan/edit/preview/page.tsx
  src/app/plan/edit/schedule/page.tsx
  src/app/plan/success/page.tsx
  src/app/plan/view/page.tsx
  src/components/feature/searchNav.tsx
  src/components/form/plan/planDetailForm.tsx
  src/components/form/plan/planRegion.tsx
  src/components/form/plan/planReplyForm.tsx
  src/components/form/searchInput.tsx
  src/components/plan/searchAll.tsx
  src/components/ui/planListItem.tsx
  src/components/ui/removeTag.tsx
  src/data/actions/plan.ts
  src/hook/useSearchHandler.ts
  src/types/plan.ts
  src/zustand/planStore.ts
Labels: 🛠️ refactor, ✨feat

#175 💄 style: 로딩페이지 설정
  src/app/layout.tsx
Labels: 🎨 style

#204 ✨ feat: 폼 리뷰 삭제 기능 추가
  api/dbinit/team/uploadFiles/user-default.webp
  src/app/feed/new/page.tsx
  src/app/plan/view/layout.tsx
  src/app/plan/view/page.tsx
  src/components/feature/drawerBtn.tsx
  src/components/feature/selectBookmark.tsx
  src/components/feature/viewItem.tsx
  src/components/form/reviewDetailForm.tsx
  src/components/form/reviewFormAll.tsx
  src/components/ui/scheduleView.tsx
  src/data/actions/review.ts
  src/data/functions/plan.ts
  src/data/functions/review.ts
  src/data/functions/travel.ts
  src/lib/api/weather.ts
Labels: 🛠️ refactor, ✨feat

#205 ✨ feat: 날짜 변경 시 검색 상태 초기화 기능 추가
  src/app/plan/edit/preview/page.tsx
  src/components/feature/fillScheduleCard.tsx
  src/components/plan/categorySelect.tsx
  src/components/plan/previewContent.tsx
  src/components/plan/searchAll.tsx
  src/components/ui/dayScheduleCard.tsx
  src/components/ui/planListItem.tsx
  src/hook/useContentDetail.ts
  src/hook/usePlanSchedule.ts
  src/hook/useSearchHandler.ts
  src/hook/useSearchReset.ts
  src/hook/useTravelData.ts
  src/types/plan.ts
Labels: 🛠️ refactor, ✨feat

#208 ♻️ refactor: 필요없는 요소 제거 및 변수 추가
  src/app/photomap/view/mapcom/depth/koreaMap.tsx
  src/app/photomap/view/mapcom/depth/koreaMapImgProto.tsx
  src/app/photomap/view/mapcom/depth/koreaMapProto.tsx
  src/app/photomap/view/mapcom/depth/map.svg
  src/app/photomap/view/mapcom/depth/photoweb.ts
  src/app/photomap/view/mapcom/depth/svgPath.tsx
  src/app/photomap/view/page.tsx
  src/types/api.ts
Labels: 🎨 style

#217 ♻️ refactor: 장소관련 data-contentid 추가연결
  src/components/feature/feedDetailContent.tsx
  src/components/feature/locationModal.tsx
  src/components/feature/selectWriteReview.tsx
  src/components/feature/viewItem.tsx
  src/components/form/reviewDetailForm.tsx
  src/components/form/reviewFormAll.tsx
  src/components/form/reviewSelect.tsx
  src/data/actions/review.ts
  src/types/review.ts
Labels: ✅ test, 🛠️ refactor

#222 ✨ feat: 여행리뷰관련 댓글 수정 및 삭제
  src/components/feature/commentDeleteForm.tsx
  src/components/feature/commentEditForm.tsx
  src/components/feature/feedContent.tsx
  src/components/feature/feedDetailContent.tsx
  src/components/ui/commentItem.tsx
  src/data/actions/reply.ts
Labels: ✨feat

#223 ✨ feat: 여행계획 성공페이지에 홈버튼 추가
  src/app/plan/success/page.tsx
  src/components/feature/selectMypage.tsx
  src/components/form/plan/planDetailForm.tsx
  src/components/form/searchInput.tsx
  src/components/plan/planDetailContent.tsx
  src/components/plan/searchAll.tsx
  src/components/plan/searchResult.tsx
  src/components/plan/searchSection.tsx
  src/components/ui/randomItem.tsx
  src/data/functions/travel.ts
Labels: 🛠️ refactor, ✨feat

#227 🐛 bug: 댓글 프로필 사진 출력되지 않는 오류 해결
  src/components/feature/feedDetailContent.tsx
  src/components/ui/commentItem.tsx
Labels: 🐞 bug

#228 ✨ feat: 날씨 API 관련 함수 수정
  src/components/feature/locationWeatherBox.tsx
  src/data/functions/weather.ts
  src/lib/api/location.ts
  src/lib/api/weather.ts
  src/lib/convertToGrid.ts
  src/types/weather.ts
Labels: 🐞 bug, 🛠️ refactor
