Repository FRONTENDBOOTCAMP-13th/Final-06-6PM, pull requests merged in 2025-08, with the labels that each got.

#230 ✨ feat: 마이페이지 편집
  src/app/(auth)/login/page.tsx
  src/app/mypage/edit/page.tsx
  src/app/mypage/page.tsx
  src/components/feature/myPassword.tsx
  src/components/feature/selectMypage.tsx
  src/components/form/profileItemEdit.tsx
  src/components/form/singUpForm.tsx
  src/components/ui/profileItem.tsx
  src/data/actions/user.ts
  src/data/functions/user.ts
  src/types/user.ts
  src/zustand/userStore.ts
Labels: 🎨 style, 🐞 bug, ✨feat

#232 🧪 test: 여행계획 페이지에 네이버지도 연동
  package-lock.json
  package.json
  src/app/plan/test/page.tsx
  src/components/feature/fillScheduleCard.tsx
  src/components/plan/naverMap.tsx
Labels: ✅ test, ✨feat

#237 ✨ feat: 북마크 기능 점검 및 마이페이지 추가 임시커밋
  src/components/feature/feedContent.tsx
  src/components/feature/feedDetailContent.tsx
  src/components/feature/selectBookmark.tsx
  src/components/feature/toggleComponents.tsx
  src/data/functions/bookmark.ts
Labels: ✨feat

#239 ♻️ refactor: 회원업데이트 함수 폼액션 변경
  src/components/feature/homePlanItem.tsx
  src/components/form/imageUploader.tsx
  src/components/form/profileItemEdit.tsx
  src/components/form/singUpForm.tsx
  src/data/actions/user.ts
Labels: 🐞 bug, 🛠️ refactor

#240 🐳 chore: DB데이터 수정
  api/dbinit/team/data.json
Labels: ⚙️ setting

#241 🐳 chore: DB데이터 추가수정
  api/dbinit/team/data.json
Labels: ⚙️ setting

#242 🐛 bug: 파일경로 카멜케이스 준수
  api/dbinit/team/data.json
Labels: 🐞 bug, 📜 docs

#243 🐳 chore: DB기초데이터 게시글 ID연결 및 프로필사진 수정
  api/dbinit/team/data.json
  api/dbinit/team/uploadFiles/seoul1.jpg
  api/dbinit/team/uploadFiles/seoul2.jpg
  api/dbinit/team/uploadFiles/seoul3.jpg
  api/dbinit/team/uploadFiles/seoul4.jpg
  api/dbinit/team/uploadFiles/seoul5.jpg
  api/dbinit/team/uploadFiles/seoul6.jpg
  api/dbinit/team/uploadFiles/ulsan1.jpg
  api/dbinit/team/uploadFiles/ulsan2.jpg
  api/dbinit/team/uploadFiles/ulsan3.jpg
  api/dbinit/team/uploadFiles/ulsan4.jpg
Labels: ⚙️ setting, 📜 docs

#245 🐳 chore: DB데이터 구조조정
  api/dbinit/team/data.json
  src/components/feature/feedContent.tsx
  src/components/feature/feedDetailContent.tsx
  src/components/feature/viewItem.tsx
  src/components/feature/viewItemSkeleton.tsx
  src/components/form/profileItemEdit.tsx
  src/components/ui/commentItem.tsx
  src/components/ui/commentitemSkeleton.tsx
  src/components/ui/profileItem.tsx
  src/components/ui/randomItem.tsx
  src/components/ui/randomItemSkeleton.tsx
Labels: 📜 docs, 🛠️ refactor

#248 ✨ feat: 필터링(최신순, 오래된순) 구현
  src/app/review/(write)/new/ReviewPage.tsx
  src/components/feature/dropdownItem.tsx
  src/components/feed/feedContent.tsx
Labels: ✨feat

#249 🐳 chore: db데이터 contentID 재설정
  api/dbinit/team/data.json
  src/components/feed/feedContent.tsx
  src/components/form/plan/planDetailForm.tsx
  src/components/plan/searchAll.tsx
Labels: 🎨 style, 🛠️ refactor

#252 ✨ feat: 네이버지도에 여행장소 연동
  src/components/plan/dayScheduleCard.tsx
  src/components/plan/fillScheduleCard.tsx
  src/components/plan/naverMap.tsx
  src/components/plan/planDetailContent.tsx
  src/components/plan/scheduleContent.tsx
Labels: ✨feat

#255 ✨ feat: 장소 북마크 기능 추가
  src/app/(auth)/login/page.tsx
  src/components/Footer.tsx
  src/components/feature/locationModal.tsx
  src/components/form/mypage/profileItemEdit.tsx
  src/components/home/drawerItem.tsx
  src/components/home/homePlanItem.tsx
  src/components/home/randomItem.tsx
  src/components/ui/btn.tsx
  src/data/actions/bookmark.ts
  src/types/bookmark.ts
  src/types/user.ts
Labels: 🎨 style, 🛠️ refactor, ✨feat

#260 ♻️ refactor: 지도생성 페이지 관련 크기 조정 및 인라인스타일요소 테일윈드로 변경
  src/app/photomap/edit/layout.tsx
  src/app/photomap/edit/page.tsx
  src/app/photomap/layout.tsx
  src/app/photomap/page.tsx
  src/app/photomap/view/layout.tsx
  src/app/photomap/view/page.tsx
  src/components/home/drawerItem.tsx
  src/components/photoweb/koreaMap.tsx
  src/components/photoweb/koreaMapImgProto.tsx
  src/components/photoweb/koreaMapProto.tsx
  src/components/ui/dayItem.tsx
  src/lib/getDday.ts
Labels: 🎨 style, 🛠️ refactor

#261 ✨ feat: 나의 장소 북마크 삭제 기능 추가
  src/app/plan/new/page.tsx
  src/components/feature/locationModal.tsx
  src/components/feed/feedContent.tsx
  src/components/mypage/placeCardSkeleton.tsx
  src/components/mypage/placeItem.tsx
  src/components/mypage/placePlusItem.tsx
  src/components/mypage/selectBookmark.tsx
  src/components/plan/categoryList.tsx
  src/components/plan/modifyScheduleContent.tsx
  src/components/plan/placeCard.tsx
  src/components/plan/searchAll.tsx
  src/data/actions/bookmark.ts
Labels: 🎨 style, 🛠️ refactor, ✨feat

#262 🐛 bug: daylist 타입에러 수정
  src/components/plan/modifyScheduleContent.tsx
  src/components/plan/previewContent.tsx
Labels: 🐞 bug

#271 ♻️ refactor: 지도 URL 코드 수정
  src/components/photoweb/koreaMap.tsx
Labels: 🛠️ refactor

#273 ✨ feat: 사용자 인증 토큰 갱신 기능 추가
  src/app/feed/[id]/edit/page.tsx
  src/app/mypage/(view)/layout.tsx
  src/app/mypage/(view)/page.tsx
  src/app/photomap/layout.tsx
  src/app/plan/edit/preview/page.tsx
  src/app/plan/layout.tsx
  src/app/plan/page.tsx
  src/app/review/(write)/new/layout.tsx
  src/components/feature/locationModal.tsx
  src/components/feature/loginStatusConfirm.tsx
  src/components/feed/commentEditForm.tsx
  src/components/feed/commentForm.tsx
  src/components/form/auth/loginForm.tsx
  src/components/form/mypage/bookAndReview.tsx
  src/components/form/mypage/profileItemEdit.tsx
  src/components/home/drawerItem.tsx
  src/components/home/randomItem.tsx
  src/data/actions/user.ts
  src/types/user.ts
  src/zustand/userStore.ts
Labels: 🛠️ refactor, ✨feat

#276 ♻️ refactor: 레이아웃, 404페이지 컴포넌트 분리
  src/app/layout.tsx
  src/app/not-found.tsx
  src/components/ClientLayout.tsx
Labels: 🛠️ refactor

#279 Refactor/allpages/psy
  api/dbinit/team/data.json
  src/app/home/page.tsx
  src/components/Navbar.tsx
  src/components/feature/loginStatusConfirm.tsx
  src/components/feed/commentDeleteForm.tsx
  src/components/feed/commentEditForm.tsx
  src/components/feed/commentForm.tsx
  src/components/feed/commentItem.tsx
  src/components/feed/feedContent.tsx
  src/components/home/homePlanItem.tsx
  src/components/home/randomItem.tsx
  src/components/mypage/bookmarkContent.tsx
  src/components/plan/searchAll.tsx
  src/components/plan/searchNav.tsx
Labels: 🎨 style, 🛠️ refactor

#288 ♻️ refactor: 날짜 관련 함수 처리
  src/components/home/serverLocation.tsx
  src/data/functions/weather.ts
  src/lib/baseTime.ts
  src/lib/getDday.ts
  src/lib/todayDate.ts
Labels: 🛠️ refactor

#290 ✨ feat: 북마크 기능 내 콘텐츠 타입 추가
  src/components/feature/locationModal.tsx
  src/components/feature/viewItem.tsx
  src/components/form/review/reviewSelect.tsx
  src/components/home/drawerItem.tsx
  src/components/home/randomItem.tsx
  src/components/mypage/bookmarkContent.tsx
  src/components/mypage/placeItem.tsx
  src/components/mypage/selectBookmark.tsx
  src/components/mypage/selectMypage.tsx
  src/components/ui/dayItem.tsx
  src/data/actions/bookmark.ts
  src/types/bookmark.ts
  src/types/review.ts
Labels: ✅ test, 🛠️ refactor, ✨feat

#289 ✨ feat: 여행일정 장소 삭제 기능 구현
  src/components/plan/dayScheduleCard.tsx
  src/components/plan/fillScheduleCard.tsx
  src/components/plan/modifyScheduleContent.tsx
  src/components/plan/planDetailContent.tsx
  src/components/plan/planListItem.tsx
Labels: 🛠️ refactor, ✨feat

#294 💄 style: 로고 파일을 PNG에서 SVG로 변경
  public/images/logo.png
  public/images/logo.svg
  src/app/(auth)/login/page.tsx
  src/components/ClientLayout.tsx
Labels: 🎨 style

#298 ♻️ refactor: 마이페이지 여행 일정 정렬 코드 추가
  src/components/mypage/selectMypage.tsx
Labels: 🛠️ refactor

#300 Refator/qa allpages/psy
  src/components/form/mypage/bookAndReview.tsx
  src/components/form/review/reviewSelect.tsx
  src/components/mypage/bookmarkContent.tsx
  src/components/mypage/bookmarkItem.tsx
  src/components/mypage/selectReviewTab.tsx
  src/components/review/selectWriteReview.tsx
Labels: 🛠️ refactor, ✨feat

#308 ♻️ refactor: 북마크와 기록페이지 필터링 변경
  src/app/review/(write)/new/ReviewPage.tsx
  src/components/feature/reviewdropdownItem.tsx
  src/components/mypage/selectBookmark.tsx
Labels: 🛠️ refactor

#314 🐳 chore: data.json 재세팅
  api/dbinit/team/data.json
  api/dbinit/team/uploadFiles/busan1.webp
  api/dbinit/team/uploadFiles/busan2.webp
  api/dbinit/team/uploadFiles/busan3.webp
  api/dbinit/team/uploadFiles/busan4.webp
  api/dbinit/team/uploadFiles/busan5.webp
  api/dbinit/team/uploadFiles/busan6.webp
  api/dbinit/team/uploadFiles/daejeon1.webp
  api/dbinit/team/uploadFiles/daejeon2.webp
  api/dbinit/team/uploadFiles/daejeon3.webp
  api/dbinit/team/uploadFiles/daejeon4.webp
  api/dbinit/team/uploadFiles/daejeon5.webp
  api/dbinit/team/uploadFiles/gyeongju1.webp
  api/dbinit/team/uploadFiles/gyeongju2.webp
  api/dbinit/team/uploadFiles/gyeongju3.webp
  api/dbinit/team/uploadFiles/gyeongju4.webp
  api/dbinit/team/uploadFiles/gyeongju5.webp
  api/dbinit/team/uploadFiles/gyeongju6.webp
  api/dbinit/team/uploadFiles/gyeongju7.webp
  api/dbinit/team/uploadFiles/gyeongju8.webp
  api/dbinit/team/uploadFiles/seoul1.jpg
  api/dbinit/team/uploadFiles/seoul1.webp
  api/dbinit/team/uploadFiles/seoul2.jpg
  api/dbinit/team/uploadFiles/seoul2.webp
  api/dbinit/team/uploadFiles/seoul3.jpg
  api/dbinit/team/uploadFiles/seoul3.webp
  api/dbinit/team/uploadFiles/seoul4.jpg
  api/dbinit/team/uploadFiles/seoul4.webp
  api/dbinit/team/uploadFiles/seoul5.jpg
  api/dbinit/team/uploadFiles/seoul5.webp
  api/dbinit/team/uploadFiles/seoul6.jpg
  api/dbinit/team/uploadFiles/ulsan1.jpg
  api/dbinit/team/uploadFiles/ulsan1.webp
  api/dbinit/team/uploadFiles/ulsan2.jpg
  api/dbinit/team/uploadFiles/ulsan2.webp
  api/dbinit/team/uploadFiles/ulsan3.jpg
  api/dbinit/team/uploadFiles/ulsan3.webp
  api/dbinit/team/uploadFiles/ulsan4.jpg
  api/dbinit/team/uploadFiles/ulsan4.webp
  api/dbinit/team/uploadFiles/ulsan5.webp
  api/dbinit/team/uploadFiles/ulsan6.webp
  api/dbinit/team/uploadFiles/ulsan7.webp
  api/dbinit/team/uploadFiles/ulsan8.webp
  api/dbinit/team/uploadFiles/ulsan9.webp
  api/dbinit/team/uploadFiles/user-ah.jpg
  api/dbinit/team/uploadFiles/user-hj.png
  api/dbinit/team/uploadFiles/user-muzi.png
  api/dbinit/team/uploadFiles/user-neo.png
  api/dbinit/team/uploadFiles/user-si.png
  api/dbinit/team/uploadFiles/user-sy.jpg
  src/app/review/success/page.tsx
  src/components/feature/toggleComponents.tsx
  src/components/feature/viewItem.tsx
  src/components/form/auth/loginForm.tsx
  src/components/mypage/bookmarkItem.tsx
  src/components/mypage/selectBookmark.tsx
  src/components/mypage/selectMypage.tsx
  src/components/plan/successLottie.tsx
  src/lottie/Success.json
Labels: ⚙️ setting

#315 💄 style: 로딩페이지 로고 추가, 애니메이션 수정, 스와이퍼 수정
  package-lock.json
  package.json
  public/images/airplane.svg
  public/images/car.svg
  public/images/typo-loading.svg
  src/components/ClientLayout.tsx
  src/components/feature/viewItem.tsx
  src/styles/globals.css
Labels: 🎨 style, 🛠️ refactor

#319 💄 style: 로딩 페이지 수정
  public/images/favicon.svg
  public/images/subtitle.svg
  public/images/typo-loading.svg
  src/components/ClientLayout.tsx
  src/components/home/loadingLottie.tsx
  src/lottie/loading-Dot.json
Labels: 🎨 style

#318 📝 docs: 리드미 파일 업데이트
  README.md
  public/images/teamprofile/ah.png
  public/images/teamprofile/hj.png
  public/images/teamprofile/si.png
  public/images/teamprofile/sy.png
Labels: 📜 docs

#327 🖥️ a11y: 여행일정페이지 웹접근성 개선
  public/images/place.png
  public/images/sea.png
  public/images/traveldiary.png
  public/images/user1.png
  public/images/user2.png
  public/images/user3.png
  public/images/user4.png
  public/images/user5.png
  src/app/(auth)/login/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/feed/(list)/page.tsx
  src/app/feed/[id]/page.tsx
  src/app/layout.tsx
  src/app/mypage/(edit)/bookmark/page.tsx
  src/app/mypage/(edit)/edit/page.tsx
  src/app/mypage/(edit)/review/page.tsx
  src/app/mypage/(view)/page.tsx
  src/app/photomap/page.tsx
  src/app/plan/[id]/layout.tsx
  src/app/plan/[id]/modify/page.tsx
  src/app/plan/[id]/page.tsx
  src/app/plan/dates/page.tsx
  src/app/plan/edit/schedule/page.tsx
  src/app/plan/edit/search/page.tsx
  src/app/plan/page.tsx
  src/app/plan/success/page.tsx
  src/app/review/(write)/[id]/page.tsx
  src/app/review/(write)/new/page.tsx
  src/app/review/edit/[id]/page.tsx
  src/app/review/success/page.tsx
  src/components/Footer.tsx
  src/components/Header.tsx
  src/components/feature/backButton.tsx
  src/components/feature/shareBtn.tsx
  src/components/feature/toggleComponents.tsx
  src/components/feature/viewItem.tsx
  src/components/feed/commentForm.tsx
  src/components/feed/feedDetailContent.tsx
  src/components/form/review/reviewImg.tsx
  src/components/form/review/reviewStar.tsx
  src/components/form/review/reviewTag.tsx
  src/components/form/searchInput.tsx
  src/components/mypage/bookmarkItem.tsx
  src/components/mypage/drawerMypage.tsx
  src/components/mypage/profileItem.tsx
  src/components/mypage/selectMypage.tsx
  src/components/photoweb/koreaMap.tsx
  src/components/plan/destinationCard.tsx
  src/components/plan/drawerPlanBtn.tsx
  src/components/plan/planListItem.tsx
  src/components/ui/dayItem.tsx
  src/styles/globals.css
Labels: 🖥️ a11y, 🛠️ refactor

#328 💄 style: 인트로 페이지 디자인 개선
  public/images/logo.svg
  src/app/intro/page.tsx
Labels: 🎨 style

#330 💄 style: 메타태그 재설정
  public/images/travel-diary.png
  public/images/traveldiary.png
  src/app/layout.tsx
  src/app/plan/[id]/layout.tsx
  src/app/plan/dates/layout.tsx
  src/components/feature/locationModal.tsx
  src/components/feature/viewItemSkeleton.tsx
  src/components/form/plan/planDetailForm.tsx
  src/components/form/review/reviewImg.tsx
  src/components/home/loginCkeck.tsx
  src/components/mypage/placeItem.tsx
  src/components/mypage/selectReviewTab.tsx
  src/components/plan/drawerPlanBtn.tsx
  src/components/plan/modifyScheduleContent.tsx
  src/components/plan/planListItem.tsx
  src/components/review/selectWriteReview.tsx
  src/data/actions/bookmark.ts
  src/data/actions/user.ts
  src/hook/useTravelData.ts
Labels: 🖥️ a11y, 🛠️ refactor

#332 💄 style: 인덱스페이지 스타일링 조정
  src/app/intro/page.tsx
  src/app/not-found.tsx
  src/app/plan/[id]/layout.tsx
  src/app/plan/[id]/page.tsx
  src/components/ClientLayout.tsx
  src/components/plan/planDetailContent.tsx
  src/components/plan/planDetailContentSkeleton.tsx
  src/components/plan/scheduleContent.tsx
Labels: 🎨 style, 🛠️ refactor

#335 📝 docs: readme 수정
  README.md
  public/images/readme/feed.gif
  public/images/readme/home.gif
  public/images/readme/login.gif
  public/images/readme/mypagebookmark.gif
  public/images/readme/photomap.gif
  public/images/readme/plan.gif
  public/images/readme/plan2.gif
  public/images/readme/plan3.gif
  public/images/readme/plan4.gif
  public/images/readme/plan5.gif
  public/images/readme/review.gif
  public/images/readme/review2.gif
  public/images/travel-banner.png
Labels: 📜 docs

#341 📝 docs: readme 이미지 수정
  README.md
Labels: 📜 docs

#345 🐛 bug: 인트로 페이지 깃허브 링크 수정
  src/app/intro/page.tsx
Labels: 🐞 bug

#346 🐛 bug: 글 작성 이후 planId연동
  src/components/review/successLink.tsx
  src/data/actions/review.ts
Labels: 🐞 bug

#351 🐛 bug: ios 3차 터치 처리
  src/components/photoweb/koreaMap.tsx
Labels: 🐞 bug
